<Project>

	<PropertyGroup>
		<RootNamespace>MongoFramework</RootNamespace>

		<Company>Turner Software</Company>

		<PackageId>$(AssemblyName)</PackageId>
		<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageIcon>icon.png</PackageIcon>
		<PackageProjectUrl>https://github.com/mape1402/mongo-framework</PackageProjectUrl>
		<RepositoryUrl>https://github.com/mape1402/mongo-framework</RepositoryUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageBaseTags>mongo;mongodb;data;database;orm</PackageBaseTags>

		<!-- SourceLink Support -->
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<DebugType>embedded</DebugType>

		<LangVersion>Latest</LangVersion>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.1.1" PrivateAssets="All" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\..\images\$(PackageIcon)" Pack="true" PackagePath="/" />
		<None Include="..\..\README.md" Pack="true" PackagePath="/" />
	</ItemGroup>

</Project>
